# Generated by Django 5.1.5 on 2025-01-20 15:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Formato de placa inválido (solo mayúsculas, números y guiones).', regex='^[A-Z0-9-]{6,10}$')], verbose_name='Placa del Vehículo')),
                ('cliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente Asociado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehiculos', to='core.tipovehiculo', verbose_name='Tipo de Vehículo')),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
            },
        ),
    ]
