# Generated by Django 5.1.5 on 2025-01-20 15:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroParqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora de Entrada')),
                ('fecha_salida', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y Hora de Salida')),
                ('total_cobro', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Total Cobrado')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('baja', 'Baja'), ('facturado', 'Facturado')], default='activo', max_length=20, verbose_name='Estado del Registro')),
                ('usuario_registra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que Registró')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_parqueo', to='vehiculos.vehiculo', verbose_name='Vehículo Asociado')),
            ],
            options={
                'verbose_name': 'Registro de Parqueo',
                'verbose_name_plural': 'Registros de Parqueo',
            },
        ),
    ]
