# Generated by Django 5.1.4 on 2025-03-18 13:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroparqueo',
            name='placa',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='Formato de placa inválido (solo mayúsculas, números y guiones).', regex='^[A-Z0-9]{6,10}$')], verbose_name='Placa del Vehículo'),
        ),
    ]
