# Generated by Django 5.1.4 on 2025-01-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parqueo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroparqueo',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('baja', 'Eliminado'), ('facturado', 'Facturado')], default='activo', max_length=20, verbose_name='Estado del Registro'),
        ),
    ]
