# Generated by Django 5.1.4 on 2025-02-11 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('parqueo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroparqueo',
            name='tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.tipovehiculo', verbose_name='Tipo de Vehículo'),
        ),
    ]
