# Generated by Django 5.1.4 on 2025-02-11 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('cancelado', 'Cancelado'), ('facturado', 'Facturado')], default='activo', max_length=20, verbose_name='Estado del Ticket'),
        ),
    ]
